worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    client_max_body_size 100m;

    server {
        listen 100;
        server_name lllyw.cn www.lllyw.cn;

        location /api/ {
            proxy_pass http://backend:9025/api/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_cache off;
            chunked_transfer_encoding on;
            proxy_read_timeout 1860s;
            proxy_send_timeout 1860s;
        }

        location ^~ /assets/ {
            root /usr/share/nginx/html;
            try_files $uri =404;
        }
        location ~ "^/([A-Za-z0-9]{6})/(.*)$" {
            root /opt/code_deploy;
            try_files /$1/$2 /$1/index.html =404;
        }

        location ~ "^/([A-Za-z0-9]{6})/?$" {
            root /opt/code_deploy;
            try_files /$1/index.html =404;
        }

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
}
