server:
  port: 9025
  servlet:
    context-path: /api

spring:
  application:
    name: ai-app-generation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3406/ai_app_generation?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lyw666

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true  # 严格遵守JSON Schema
      response-format: json_object #json格式输出
      max-retries: 2
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.lyw.appgeneration.controller
# knife
knife4j:
  enable: true
  setting:
    language: zh_cn