-- 第一版只有 user、app、chat_history，先建立新版记忆表，再执行后续增量迁移。
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS app_memory_summary (
    id BIGINT NOT NULL PRIMARY KEY,
    appId BIGINT NOT NULL,
    summary MEDIUMTEXT NULL,
    lastSummarizedId BIGINT DEFAULT 0 NOT NULL,
    summaryTokens INT DEFAULT 0 NOT NULL,
    failCount INT DEFAULT 0 NOT NULL,
    nextRetryTime DATETIME NULL,
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updateTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    isDelete TINYINT DEFAULT 0 NOT NULL,
    UNIQUE KEY uk_appId (appId)
) COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS app_memory (
    id BIGINT NOT NULL PRIMARY KEY,
    userId BIGINT NOT NULL,
    appId BIGINT NULL,
    type VARCHAR(32) NOT NULL DEFAULT 'USER_PREFERENCE',
    name VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    evidenceType VARCHAR(16) NOT NULL DEFAULT 'EXPLICIT',
    evidenceCount INT NOT NULL DEFAULT 1,
    lastEvidenceTurnId BIGINT NULL,
    createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDelete TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_userId_type_name (userId, type, name)
) COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS app_memory_extract_cursor (
    id BIGINT NOT NULL PRIMARY KEY,
    appId BIGINT NOT NULL,
    userId BIGINT NOT NULL,
    lastExtractedId BIGINT NOT NULL DEFAULT 0,
    failCount INT NOT NULL DEFAULT 0,
    nextRetryTime DATETIME NULL,
    createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDelete TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_appId (appId)
) COLLATE=utf8mb4_unicode_ci;
