name: ai-codegen-rag

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: ai-codegen-pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_codegen_rag
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: lyw666
    ports:
      - "5432:5432"
    volumes:
      - ./.data/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ai_codegen_rag"]
      interval: 5s
      timeout: 5s
      retries: 10
